source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'LFRequest_Example' do
  pod 'LFRequest', :path => '../'
  
  # 库依赖
  pod 'AFNetworking'
  pod 'YYModel'
  pod 'YYCache'
  
  # demo依赖
  pod 'Masonry'
end
