use_frameworks!

platform :ios, '8.0'

target 'LFRequest_Example' do
  pod 'LFRequest', :path => '../'

  target 'LFRequest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
