source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'LFRequest_Example' do
  pod 'LFRequest', :path => '../'
  
  pod 'AFNetworking'
  pod 'YYModel'
  pod 'YYCache'
end
